export const QUIPS: string[] = [
  'Fun fact: the longest bar in the world is 684 feet long — Liar\'s Club in Montana 🍺',
  '💡 Tip: loud wrong answers are still entertaining',
  'The average pub quiz team has 6 members. You\'re statistically normal.',
  'Beer was so important in ancient Egypt, workers were paid with it.',
  'Trivia time is the one time no one checks their phone. Probably.',
  'The word "trivia" comes from Latin trivium — where three roads meet.',
  'Fun fact: Cheers ran for 11 seasons and won 111 Emmy nominations.',
  '💡 Whisper your answer to your teammates first. Shouting it defeats the purpose.',
  'The world\'s oldest known beer recipe is over 4,000 years old. It\'s Sumerian.',
  'IPAs get their bitterness from hops. Fun to taste. Less fun to explain.',
  'Fun fact: Jeopardy! has been on air since 1964. Alex Trebek hosted for 37 years.',
  '💡 If in doubt, blame the designated wrong-answerer on your team.',
  'Canada has more lakes than the rest of the world combined.',
  'There are more possible games of chess than atoms in the observable universe.',
  '💡 Conferring loudly with your team is a feature, not a bug.',
  'Fun fact: Oktoberfest consumes about 7 million litres of beer each year.',
  'The shortest war in history lasted 38–45 minutes. Anglo-Zanzibar, 1896.',
  '💡 The team with the most confident wrong answer always gets applause.',
  'Australia is the only continent that is also a single country.',
  'Fun fact: Scotland\'s national animal is the unicorn. Seriously.',
  'The Eiffel Tower can be 15 cm taller in summer due to thermal expansion.',
  '💡 Good pub quiz strategy: answer fast, argue later.',
  'Honey never spoils. Archaeologists found 3,000-year-old honey that was still edible.',
  'Fun fact: Oxford University is older than the Aztec Empire.',
  'The average person walks past 36 murderers in their lifetime. Enjoy your next stroll! 🚶',
  '💡 A wrong answer said with conviction is better than silence.',
  'Before alarm clocks, people hired "knocker-uppers" to tap on windows each morning.',
]
